#!/usr/bin/env bash

#PBS -N log_test_calculator
#PBS -q normal
#PBS -l select=1:ngpus=1
#PBS -l walltime=00:10:00
#PBS -j oe

# submit PBS job with `qsub -P <project_id> <this_script>`

cd $PBS_O_WORKDIR
mkdir -p log

module load cuda/12.6.2

export HF_HOME="$HOME/scratch/hf_home"
MAMBA="$HOME/miniforge3/condabin/mamba"

$MAMBA run -n leanlm \
    python leanlm/model.py |& tee log/test.log
