#!/usr/bin/env bash
MESSAGE=$(cat)

if [ -n "$MESSAGE" ]; then
  curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
       -H "Content-Type: application/json" \
       -d "{\"chat_id\": \"${TG_CHAT}\", \"text\": \"${MESSAGE}\"}" \
       -w "\nHTTP status: %{http_code}\n"
fi