#!/usr/bin/env bash

#PBS -N log_deepseekr1_7b_lora
#PBS -q normal
#PBS -l select=1:ngpus=1
#PBS -l walltime=23:59:59
#PBS -j oe

# submit PBS job with `qsub -P <project_id> <this_script>`

cd $PBS_O_WORKDIR
mkdir -p log

module load cuda/12.6.2

while true; do
    nvidia-smi > log/gpu.log
    sleep 5
done &

export HF_HOME="$HOME/scratch/hf_home"
MAMBA="$HOME/miniforge3/condabin/mamba"

$MAMBA run -n leanlm uv run \
    python -m leanlm.recipes.deepseekr1_7b_lora train |& tee log/run_deepseekr1_7b_lora.log
