#!/usr/bin/env bash

#PBS -N log_train_calculator
#PBS -q normal
#PBS -l select=1:ngpus=8:mem=128GB:mpiprocs=8:ompthreads=1
#PBS -l walltime=23:59:59
#PBS -j oe

# submit PBS job with `qsub -P <project_id> <this_script>`

cd $PBS_O_WORKDIR
mkdir -p log

module load cuda/12.6.2

while true; do
    nvidia-smi > log/gpu.log
    sleep 10
done &

$HOME/miniforge3/condabin/mamba run -n leanlm \
    accelerate launch -m leanlm.run_train_calculator |& tee log/run.log