#!/usr/bin/env bash

BOT_TOKEN="xxx"
CHAT_ID="xxx"

MESSAGE=$(cat)

if [ -n "$MESSAGE" ]; then
  curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
       -H "Content-Type: application/json" \
       -d "{\"chat_id\": \"${CHAT_ID}\", \"text\": \"${MESSAGE}\"}" \
       -w "\nHTTP status: %{http_code}\n"
fi