#!/usr/bin/env bash
config_path="recipes/example1.json"
config_path=$1

export TORCH_LOGS="+dynamo"
export TORCHDYNAMO_VERBOSE=1
export NCCL_P2P_DISABLE=1
export TORCH_DISTRIBUTED_DEBUG=DETAIL
export PYTHONPATH=.
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"

PORT=$(python -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()")

log_path=$(python llmft/get_log_path_from_config.py $config_path)
mkdir -p $(dirname $log_path)

# accelerate launch --main_process_port=$PORT \
#   -m llmft.run_train $config_path 2>&1 | tee "$log_path"
python \
    -m llmft.run_train_lm $config_path 2>&1 | tee "$log_path"
